# Generated by Django 4.1.3 on 2022-12-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profile_page/'),
        ),
    ]
