# Generated by Django 4.1.3 on 2022-12-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Image',
        ),
        migrations.AddField(
            model_name='add',
            name='filename',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
