# Generated by Django 4.1.3 on 2022-12-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_remove_profile_image_add_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('commentator', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
